[package]
name = "otomo-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["TWALL9"]

[dependencies]
panic-probe = { version = "0.3", features = ["print-defmt"] }
stm32f4xx-hal = { version = "0.13.2", features = ["stm32f407", "rtic"] }

cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2.7"
alloc-cortex-m = "0.4.2"

cortex-m-rtic = "1.1.3"
rtic-monotonic = "1.0"
systick-monotonic = "1.0"

defmt = "0.3"
defmt-rtt = "0.3"

prost = { version = "0.10", default-features = false, features = ["prost-derive"] }
prost-types = { version = "0.10", default-features = false }

heapless = "0.7.16"

[build-dependencies]
prost-build = "0.10"

[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"
